name: shop
description: A simple shopping app
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

fonts:
  - family: 'Lato'
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf
        weigth: 400
      - asset: assets/fonts/Lato-Bold.ttf
        weigth: 700
  - family: 'Anton'
    fonts:
      - asset: assets/fonts/Anton-Regular.ttf
        weigth: 400
